### Day 8 - Treetop Tree House

In [305]:
import numpy as np

In [306]:
# import data
#filename = '08_test.txt'
filename = '08_data.txt'
raw = open(f'./data/{filename}').read()

In [307]:
def parse_data(data):
    data = raw.split('\n')
    data = [list(x) for x in data]
    return np.array(data, dtype=int)

data = parse_data(raw)
data

array([[3, 2, 3, ..., 1, 0, 0],
       [3, 3, 1, ..., 0, 1, 2],
       [0, 2, 3, ..., 2, 3, 2],
       ...,
       [1, 1, 0, ..., 1, 2, 3],
       [0, 0, 1, ..., 2, 0, 3],
       [1, 1, 0, ..., 2, 2, 1]])

In [308]:
def check_trees(data, i, j):
    el = data[i,j]
    lc = all(el > data[i,:j])
    rc = all(el > data[i,j+1:])
    uc = all(el > data[:i, j])
    dc = all(el > data[i+1:, j])

    return any([lc, rc, uc, dc])     

In [309]:
n, m = data.shape
mask = np.zeros_like(data)

for i in range(0,n):
    for j in range(0,m):
        if check_trees(data, i, j):
            mask[i, j] = True
print(mask)
np.sum(mask)

[[1 1 1 ... 1 1 1]
 [1 1 0 ... 0 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 0 0 ... 0 0 1]
 [1 0 1 ... 0 0 1]
 [1 1 1 ... 1 1 1]]


1695

### Part 2

In [324]:
def tree_score(data, i, j):
    el = data[i,j]
    trees_list = [data[i,:j][::-1], data[i,j+1:], data[:i, j][::-1], data[i+1:, j]]
    distance = []
    for trees in trees_list:
        dis = 0
        for d in trees:
            dis += 1
            if el <= d:
                break
        distance.append(dis)
    return np.prod(distance)

In [326]:
n, m = data.shape
score = []

for i in range(0,n):
    for j in range(0,m):
            score.append(tree_score(data, i, j))

max(score)      

287040